### ISSUE TITLE
Eu quero contribuir

### ISSUE THREAD

**Issue by PatrickLeal** [migue1neto/Standvirtual#1]
Poderia gerar o arquivos `requirements.txt` com as versões das bibliotecas usadas?

eu também fiz um [projeto ](https://github.com/PatrickLeal/olx-veiculos-web-scraping/tree/main) parecido recentemente daqui do Brasil mas foi no site da Olx e por isso gostaria de contribuir e ganhar mais experiência 👨🏽‍💻

**Comment by migue1neto** [comment]
Olá Patrick! Muito obrigado, adicionei agora. Penso que está lá tudo!

**Comment by PatrickLeal** [comment]
Obrigado.

**Comment by migue1neto** [comment]
Hoje tenho estado a testar extrair mais alguns dados do anúncios que seriam interessantes, nomeadamente o modelo do carro e data de publicação do anúncio. O problema é que essa informação apenas está contida dentro do URL de cada anúncios e são +40 mil anúncios... estou a testar extrair essa informação toda mas até agora não tenho uma solução ideal

**Comment by PatrickLeal** [comment]
> Hoje tenho estado a testar extrair mais alguns dados do anúncios que seriam interessantes, nomeadamente o modelo do carro e data de publicação do anúncio. O problema é que essa informação apenas está contida dentro do URL de cada anúncios e são +40 mil anúncios... estou a testar extrair essa informação toda mas até agora não tenho uma solução ideal

se você não salvou os links junto com as informações dos anúncios então fica muito difícil fazer isso 

a minha abordagem foi diferente, eu primeiro baixei os links dos anúncios e somente depois eu  fiz o scraping de cada link. No meu caso, o site apenas mostrava 100 páginas, o que gerava aproximadamente 5300 links por vez que eu executava o script.

**Comment by PatrickLeal** [comment]
você não precisa mandar +40 mil requisições de uma vez, eu nem recomendo que vc faça isso, você pode fazer executar o script em dias diferentes e de alguma forma não utilizar os URLs já raspados.

**Comment by migue1neto** [comment]
Exato, 40 mil num dia é impossível do mesmo IP. A minha ideia é fazer como dizes

Eu no meu script não raspo nem URL, apenas raspo a ‘página principal’ que tem o resumo de cada anúncio

**Comment by PatrickLeal** [comment]
acho que você vai ter que raspar os links dos anúncios mesmo, só depois entrar em cada URL e raspar os dados que for necessário.
